"""Writes shaders/ink_pressureN.frag: N of the Ink Blobs Jacobi pressure
iterations folded into one pass.

One iteration is p' = (pL + pR + pB + pT - div) / 4 with the neighbors
clamped to the edge. Clamping to the edge is the same as mirroring the
field about each wall, so N iterations are one fixed kernel over the
mirrored field: p_N = A^N p_0 - (A^0 + ... + A^(N-1)) div / 4, where A^k
weighs each offset by the share of k step walks that end there. A walk on
the grid is two independent walks along the diagonals, so that share is
C(k, (k+a+b)/2) * C(k, (k+a-b)/2) / 4^k for the offset (a, b).

Four is the most a pass takes on low end GPUs (Mali Midgard) before its
cost jumps, from the taps it keeps live at once.

Usage: python3 tool/generate_ink_pressure.py 4
"""

import sys
from fractions import Fraction
from math import comb
from pathlib import Path

SHADERS = Path(__file__).resolve().parent.parent / 'shaders'


def walks(k, a, b):
    """Share of k step walks from the origin that end at (a, b)."""
    u, v = k + a + b, k + a - b
    if u % 2 or v % 2 or not 0 <= u // 2 <= k or not 0 <= v // 2 <= k:
        return Fraction(0)
    return Fraction(comb(k, u // 2) * comb(k, v // 2), 4**k)


def groups(weight, radius):
    """Offsets within radius, grouped by their (equal) nonzero weight."""
    out = {}
    for a in range(-radius, radius + 1):
        for b in range(-radius, radius + 1):
            if abs(a) + abs(b) > radius:
                continue
            w = weight(a, b)
            if w:
                out.setdefault(w, []).append((a, b))
    return sorted(out.items(), key=lambda g: -g[0])


def name(axis, offset):
    return f'{axis}{"m" if offset < 0 else "p"}{abs(offset)}'


def terms(sampler, grouped):
    lines = []
    for w, offsets in grouped:
        taps = ' + '.join(
            f'texture({sampler}, vec2({name("x", a)}, {name("y", b)})).rgb'
            for a, b in offsets
        )
        lines.append(f'  s += {float(w)!r} * ({taps});')
    return '\n'.join(lines)


def shader(n):
    pressure = groups(lambda a, b: walks(n, a, b), n)
    divergence = groups(
        lambda a, b: sum((walks(j, a, b) for j in range(n)), Fraction(0)) / 4,
        n - 1,
    )
    coords = '\n'.join(
        f'  float {name(axis, o)} = mirror{axis.upper()}(i.{axis} + {float(o)!r});'
        for axis in 'xy'
        for o in range(-n, n + 1)
    )
    return f'''#version 460 core
#include <flutter/runtime_effect.glsl>
#include "ink_common.glsl"
// {n} of PRES_FRAG's Jacobi iterations in one pass, generated by
// tool/generate_ink_pressure.py. The original clamps each iteration's
// neighbors to the edge, which is the same as mirroring the field about
// each wall, so the {n} iterations are one fixed kernel over the mirrored
// field and the result is exact. scale multiplies the starting pressure,
// which folds CLEAR_FRAG into the first pass.
//
// Decoding is linear, so the weighted sum of the decoded taps is the
// decoded weighted sum of their raw colors: each tap is one fetch and one
// add, and each field is decoded once. The kernels' weights sum to 1 for
// the pressure and {n}/4 for the divergence.
uniform float scale;
uniform sampler2D uPressure;
uniform sampler2D uDivergence;
out vec4 fragColor;

// The texture coordinate of a column or row index, mirrored about -0.5 and
// size - 0.5.
float mirrorX(float x) {{
  float m = x < 0.0 ? -1.0 - x : x;
  m = m >= size.x ? 2.0 * size.x - 1.0 - m : m;
  return (m + 0.5) / size.x;
}}

float mirrorY(float y) {{
  float m = y < 0.0 ? -1.0 - y : y;
  m = m >= size.y ? 2.0 * size.y - 1.0 - m : m;
  return imageUv(vec2(0.0, (m + 0.5) / size.y)).y;
}}

float decodeSum(vec3 s, float weights) {{
  float n = dot(s, vec3(255.0 * 65536.0, 255.0 * 256.0, 255.0));
  return (n / 16777215.0 - 0.5 * weights) * 2.0 * SCALAR_RANGE;
}}

void main() {{
  vec2 i = floor(glUv(FlutterFragCoord().xy) * size);
{coords}
  vec3 s = vec3(0.0);
{terms('uPressure', pressure)}
  float p = decodeSum(s, 1.0);
  s = vec3(0.0);
{terms('uDivergence', divergence)}
  float d = decodeSum(s, {float(Fraction(n, 4))!r});
  fragColor = encodeScalar(scale * p - d);
}}
'''


if __name__ == '__main__':
    for arg in sys.argv[1:]:
        n = int(arg)
        path = SHADERS / f'ink_pressure{n}.frag'
        path.write_text(shader(n))
        print(path)
