#version 460 core
#include <flutter/runtime_effect.glsl>
#include "ink_common.glsl"
// 4 of PRES_FRAG's Jacobi iterations in one pass, generated by
// tool/generate_ink_pressure.py. The original clamps each iteration's
// neighbors to the edge, which is the same as mirroring the field about
// each wall, so the 4 iterations are one fixed kernel over the mirrored
// field and the result is exact. scale multiplies the starting pressure,
// which folds CLEAR_FRAG into the first pass.
//
// Decoding is linear, so the weighted sum of the decoded taps is the
// decoded weighted sum of their raw colors: each tap is one fetch and one
// add, and each field is decoded once. The kernels' weights sum to 1 for
// the pressure and 4/4 for the divergence.
uniform float scale;
uniform sampler2D uPressure;
uniform sampler2D uDivergence;
out vec4 fragColor;

// The texture coordinate of a column or row index, mirrored about -0.5 and
// size - 0.5.
float mirrorX(float x) {
  float m = x < 0.0 ? -1.0 - x : x;
  m = m >= size.x ? 2.0 * size.x - 1.0 - m : m;
  return (m + 0.5) / size.x;
}

float mirrorY(float y) {
  float m = y < 0.0 ? -1.0 - y : y;
  m = m >= size.y ? 2.0 * size.y - 1.0 - m : m;
  return imageUv(vec2(0.0, (m + 0.5) / size.y)).y;
}

float decodeSum(vec3 s, float weights) {
  float n = dot(s, vec3(255.0 * 65536.0, 255.0 * 256.0, 255.0));
  return (n / 16777215.0 - 0.5 * weights) * 2.0 * SCALAR_RANGE;
}

void main() {
  vec2 i = floor(glUv(FlutterFragCoord().xy) * size);
  float xm4 = mirrorX(i.x + -4.0);
  float xm3 = mirrorX(i.x + -3.0);
  float xm2 = mirrorX(i.x + -2.0);
  float xm1 = mirrorX(i.x + -1.0);
  float xp0 = mirrorX(i.x + 0.0);
  float xp1 = mirrorX(i.x + 1.0);
  float xp2 = mirrorX(i.x + 2.0);
  float xp3 = mirrorX(i.x + 3.0);
  float xp4 = mirrorX(i.x + 4.0);
  float ym4 = mirrorY(i.y + -4.0);
  float ym3 = mirrorY(i.y + -3.0);
  float ym2 = mirrorY(i.y + -2.0);
  float ym1 = mirrorY(i.y + -1.0);
  float yp0 = mirrorY(i.y + 0.0);
  float yp1 = mirrorY(i.y + 1.0);
  float yp2 = mirrorY(i.y + 2.0);
  float yp3 = mirrorY(i.y + 3.0);
  float yp4 = mirrorY(i.y + 4.0);
  vec3 s = vec3(0.0);
  s += 0.140625 * (texture(uPressure, vec2(xp0, yp0)).rgb);
  s += 0.09375 * (texture(uPressure, vec2(xm1, ym1)).rgb + texture(uPressure, vec2(xm1, yp1)).rgb + texture(uPressure, vec2(xp1, ym1)).rgb + texture(uPressure, vec2(xp1, yp1)).rgb);
  s += 0.0625 * (texture(uPressure, vec2(xm2, yp0)).rgb + texture(uPressure, vec2(xp0, ym2)).rgb + texture(uPressure, vec2(xp0, yp2)).rgb + texture(uPressure, vec2(xp2, yp0)).rgb);
  s += 0.0234375 * (texture(uPressure, vec2(xm2, ym2)).rgb + texture(uPressure, vec2(xm2, yp2)).rgb + texture(uPressure, vec2(xp2, ym2)).rgb + texture(uPressure, vec2(xp2, yp2)).rgb);
  s += 0.015625 * (texture(uPressure, vec2(xm3, ym1)).rgb + texture(uPressure, vec2(xm3, yp1)).rgb + texture(uPressure, vec2(xm1, ym3)).rgb + texture(uPressure, vec2(xm1, yp3)).rgb + texture(uPressure, vec2(xp1, ym3)).rgb + texture(uPressure, vec2(xp1, yp3)).rgb + texture(uPressure, vec2(xp3, ym1)).rgb + texture(uPressure, vec2(xp3, yp1)).rgb);
  s += 0.00390625 * (texture(uPressure, vec2(xm4, yp0)).rgb + texture(uPressure, vec2(xp0, ym4)).rgb + texture(uPressure, vec2(xp0, yp4)).rgb + texture(uPressure, vec2(xp4, yp0)).rgb);
  float p = decodeSum(s, 1.0);
  s = vec3(0.0);
  s += 0.3125 * (texture(uDivergence, vec2(xp0, yp0)).rgb);
  s += 0.09765625 * (texture(uDivergence, vec2(xm1, yp0)).rgb + texture(uDivergence, vec2(xp0, ym1)).rgb + texture(uDivergence, vec2(xp0, yp1)).rgb + texture(uDivergence, vec2(xp1, yp0)).rgb);
  s += 0.03125 * (texture(uDivergence, vec2(xm1, ym1)).rgb + texture(uDivergence, vec2(xm1, yp1)).rgb + texture(uDivergence, vec2(xp1, ym1)).rgb + texture(uDivergence, vec2(xp1, yp1)).rgb);
  s += 0.015625 * (texture(uDivergence, vec2(xm2, yp0)).rgb + texture(uDivergence, vec2(xp0, ym2)).rgb + texture(uDivergence, vec2(xp0, yp2)).rgb + texture(uDivergence, vec2(xp2, yp0)).rgb);
  s += 0.01171875 * (texture(uDivergence, vec2(xm2, ym1)).rgb + texture(uDivergence, vec2(xm2, yp1)).rgb + texture(uDivergence, vec2(xm1, ym2)).rgb + texture(uDivergence, vec2(xm1, yp2)).rgb + texture(uDivergence, vec2(xp1, ym2)).rgb + texture(uDivergence, vec2(xp1, yp2)).rgb + texture(uDivergence, vec2(xp2, ym1)).rgb + texture(uDivergence, vec2(xp2, yp1)).rgb);
  s += 0.00390625 * (texture(uDivergence, vec2(xm3, yp0)).rgb + texture(uDivergence, vec2(xp0, ym3)).rgb + texture(uDivergence, vec2(xp0, yp3)).rgb + texture(uDivergence, vec2(xp3, yp0)).rgb);
  float d = decodeSum(s, 1.0);
  fragColor = encodeScalar(scale * p - d);
}
